term xterm-256color
shell_integration enabled
allow_hyperlinks yes
editor nvim
enable_audio_bell no

font_family        Hack Nerd Font
bold_font          Hack Nerd Font Bold
italic_font        Hack Nerd Font Italic
bold_italic_font   Hack Nerd Font Bold Italic
font_size 14.0

include themes/cyberdream.conf
background_image ~/.config/kitty/gradient-bg.png
background_image_layout scaled
background_tint 0.0
background_opacity 1.0

macos_titlebar_color background
macos_thicken_font 0.75
macos_option_as_alt yes

cursor_shape block
cursor_blink_interval 0
scrollback_lines 5000
wheel_scroll_multiplier 1.5
mouse_hide_wait -1

hide_window_decorations no
draw_minimal_borders yes
enabled_layouts splits
window_padding_width 20 30
window_margin_width 0
remember_window_size no
initial_window_width 1200
initial_window_height 750

map cmd+enter new_window
map cmd+] next_window
map cmd+[ previous_window
map cmd+w close_window

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge top
tab_bar_align left
tab_bar_min_tabs 1
tab_title_max_length 25
tab_title_template " {index}: {title} "
active_tab_font_style bold
inactive_tab_font_style normal

map cmd+t new_tab
map cmd+w close_tab
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+plus change_font_size all +1.0
map cmd+minus change_font_size all -1.0
map cmd+0 change_font_size all 0
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

startup_session ~/.config/kitty/startup.conf
